# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47eeb366a8ad3641e287f8c3ba30974b2a36e66778e034a90efbb07e0e40d19e4deb52ac2ce93f0a7080700c67d877c3bca2d3921999710ee7b0a23c809881ae

test:
  secret_key_base: c2d4d525a744a0a30aeae97b54e3b421c5496cd1fb8468b6c8861584277416de963129b93d6bc69fa76653f943b55ed7165a9643ae2584b6d4a4d21071c1dbe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
